[package]
name = "first_project"
version = "0.1.0"
edition = "2021"

[dependencies]
rpassword = "7.0.0"
futures = "0.3"
logging_aspect = { path = "./logging_aspect" }
struct_display_macro = { path = "./rust_workspace/struct_display_macro" }